version: '3'

services:
  frontend:
    container_name: whatsapp_dev
    build: .
    command: yarn dev
    ports:
      - 4004:3000
    env_file:
      - ./.env.local
    volumes:
      - ./:/codebase
      - /codebase/node_modules
